# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albun_logo',
            new_name='album_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albun_title',
            new_name='album_title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='albun',
            new_name='album',
        ),
    ]
